name: kasanah_mobile
description: Kasanah Mobile App (DEV)
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  adaptive_dialog: ^1.8.2
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  date_count_down: ^2.1.0
  dio: ^5.1.1
  dotted_border: ^2.0.0+3
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_countdown_timer: ^4.1.0
  flutter_snake_navigationbar: ^0.6.1
  flutter_svg: ^2.0.5
  http: ^0.13.5
  image_picker: ^0.8.6+1
  intl: ^0.18.0
  nanoid: ^1.0.0
  onesignal_flutter: ^3.5.0
  open_filex: ^4.3.2
  otp_text_field: ^1.1.3
  package_info_plus: ^3.0.2
  path_provider: ^2.0.12
  pinput: ^2.2.21
  shared_preferences: ^2.0.17
  shimmer: ^2.0.0
  url_launcher: ^6.1.8
  dropdown_search: ^5.0.6
  qr_flutter: ^4.0.0
  permission_handler: ^10.2.0
  image_gallery_saver: ^1.7.1
  qr_code_scanner: ^1.0.1
  convex_bottom_bar: ^3.2.0
  infinite_scroll_pagination: ^3.2.0
  flutter_datetime_picker: ^1.5.1
  dependencies:
  currency_text_input_formatter: ^2.1.9
  pull_to_refresh: ^2.0.0
  loading_animation_widget: ^1.2.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/sfx/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 500
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Light.otf
        - asset: assets/fonts/poppins/Poppins-Regular.otf
        - asset: assets/fonts/poppins/Poppins-Medium.otf
        - asset: assets/fonts/poppins/Poppins-SemiBold.otf
        - asset: assets/fonts/poppins/Poppins-Bold.otf
        - asset: assets/fonts/poppins/Poppins-Black.otf